main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('add_new_post/', views.create, name='create'),
    path('detail/<int:detail_id>/', views.detail, name='detail'),
    path('delete/<int:delete_id>/', views.delete, name='delete'),
    path('search/', views.search, name='search'),
    path('rate/', views.rate, name='rate'),
]

proyekakhirkelompok3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('userauth/', include('userauth.urls')),
]

userauth/urls.py
from django.urls import path
from .views import userlogin, userregister, userlogout

app_name = 'userauth'

urlpatterns = [
	path('login/', userlogin, name = 'login'),
	path('register/', userregister, name = 'register'),
    path('logout/', userlogout, name = 'logout'),
]

main/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator, MinLengthValidator, MaxLengthValidator

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.title

class Rating(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    score = models.IntegerField(default=0, 
        validators=[
            MaxValueValidator(5),
            MinValueValidator(0),
        ]
    )

    def __str__(self):
        return str(self.pk)

userauth/models.py
from django.db import models

# Create your models here.

main/forms.py
from django.db.models import fields
from django.forms.models import ModelForm
from .models import Post
from django import forms


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body']

        widgets = {
            'title' : forms.TextInput(attrs={'class' : 'form-control'}),
            'body' : forms.Textarea(attrs={'class' : 'form-control'}),
        }

userauth/forms.py
from django import forms

class AuthForm(forms.Form):
    nama = forms.CharField(
        max_length = 300,
        widget = forms.TextInput(
            attrs = {
                'class': 'form-control',
				'placeholder': 'Masukkan username'
            }
        )
    )

    password = forms.CharField(
        max_length = 100, 
        widget = forms.PasswordInput(
            attrs = {
                'class': 'form-control',
				'placeholder': 'Masukkan password'
            }
        )
    )

main/views.py
from django.http.response import JsonResponse
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.contrib.auth.models import User 
from .models import Post, Rating
from .forms import PostForm

# Create your views here.

def index(request):
    all_news = Post.objects.all().order_by('-id')

    context = {
        'all_news':all_news,
    }

    return render(request, 'main/index.html', context)

def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        form.instance.user = request.user
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = PostForm()
    
    context = {
        'form': form
        }

    return render(request, 'main/create.html', context)

def detail(request, detail_id):
    post_detail = Post.objects.get(id=detail_id)
    author = str(post_detail.user.username)
    title = post_detail.title
    ratings = Rating.objects.filter(post=post_detail)
    ratingcount = 0
    ratingsum = 0
    for i in range (len(ratings)):
        ratingcount += 1
        ratingsum += ratings[i].score
    
    if ratingcount == 0:
        ratingret = "No Rate Yet"
    else:
        ratingret = "{average:.2f}".format(average=(ratingsum/ratingcount))

    isAuthor = False
    if request.user.is_authenticated:
        isAuthor = (author == str(request.user.username))

    context = {
        'post_detail':post_detail,
        'author':author,
        'isAuthor':isAuthor,
        'title':title,
        'rating':ratingret,
    }
    
    return render(request, 'main/detail.html', context)

def delete(request, delete_id):
    Post.objects.filter(id=delete_id).delete()
    return redirect('main:index')

def search(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        post = Post.objects.filter(title__contains=searched).order_by('-title').reverse()
        return render(request, 'main/searchresult.html', {'all_news' : post})
    else:
        return redirect('main:index')

def rate(request):
    element_id = request.POST.get('element_id')
    value = request.POST.get('value')
    post = Post.objects.get(id=element_id)
    rating = Rating.objects.filter(post=post, user=request.user).first()
    
    if rating is not None:
        rating.score = value
        rating.save()
        return JsonResponse({'success':'true', 'score':value}, safe=False)

    else:
        rating = Rating.objects.create(post=post, user=request.user, score=value)
        rating.save()
        return JsonResponse({'success':'true', 'score':value}, safe=False)

userauth/views.py
from django.shortcuts import render, redirect, resolve_url
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User 

from .forms import AuthForm

# Create your views here.
def userlogin(request):
    if (not request.user.is_anonymous):
	    return redirect(resolve_url('main:index'))

    form = AuthForm(request.POST or None)
    context = {
        'Form': form,
        'isError': False,
        'Error': '',
    }

    if (request.method == "POST"):
        account = authenticate(
            username = request.POST['nama'],
            password = request.POST['password'],
        )

        if (account == None):
            context['isError'] = True
            context['Error'] = 'Autentikasi gagal'
            context['Form'] = AuthForm()
            return render(request, 'userauth/login.html', context)
        else:
            login(request, account)
            return redirect(resolve_url('main:index'))

    return render(request, 'userauth/login.html', context)

def userregister(request):
    if (not request.user.is_anonymous):
	    return redirect(resolve_url('main:index'))

    form = AuthForm(request.POST or None)
    context = {
        'Form': form,
        'isError': False,
        'Error': '',
    }

    if (request.method == "POST"):
        account = None
        try:
            account = User.objects.get(username = request.POST['nama'])
        except:
            account = None
        if (account == None):
            new_account = User.objects.create_user(request.POST['nama'], '', request.POST['password'])
            new_account.save()
            login(request, new_account)
            return redirect(resolve_url('main:index'))
        else:
            context['isError'] = True
            context['Error'] = 'Sudah ada akun dengan username ' + request.POST['nama']
            context['Form'] = AuthForm()
            return render(request, 'userauth/register.html', context)

    return render(request, 'userauth/register.html', context)

def userlogout(request):
    logout(request)
    return redirect(resolve_url('main:index'))

main/templates/main/create.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Add New Post | HypeUI</title>
{% endblock meta %}

{% block content %}
  <br>
  <div class="postform">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-success btn-block">Submit</button>
    </form>
  </div>
{% endblock content %}

main/templates/main/detail.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Post: {{post_detail.title}} | HypeUI</title>
{% endblock meta %}

{% block content %}
<section>
    <hr>
    <div class="container">
        <h1>{{post_detail.title}}</h1>
        <h3>By: {{author}}</h3>
        <h3>Rating: {{rating}}</h3>
        <br>
        <p>{{post_detail.body}}</p>
    </div>
    <br>
    <div>
    {% if user.is_authenticated %}
        <br>
        {% if isAuthor is True %}
        <h5 style="text-align: center;">
            <a class="btn btn-danger" href="{% url 'main:delete' post_detail.id%}" title="">
                Klik Tombol Untuk Menghapus Post
            </a>
        </h5>
        <br>
        {% else %}
        <div style="text-align: center;">
            <hr>
            <h3 style="font-weight: bold;">Beri Rating</h3>
            <form class="rate-form" action="" method="POST" id="{{post_detail.id}}">
                {% csrf_token %}
                <button type="submit" class="fa fa-star fa-3x my-btn checked" id="first"></button>
                <button type="submit" class="fa fa-star fa-3x my-btn checked" id="second"></button>
                <button type="submit" class="fa fa-star fa-3x my-btn checked" id="third"></button>
                <button type="submit" class="fa fa-star fa-3x my-btn" id="fourth"></button>
                <button type="submit" class="fa fa-star fa-3x my-btn" id="fifth"></button>
            </form>
            <br>
            <div id="confirm-box"></div>
            <hr>
            <br><br>
        </div>
        {% endif %}
    {% endif %}
    </div>
</section>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'main/js/script.js' %}"></script>
{% endblock content %}

main/templates/main/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Beranda | HypeUI</title>
{% endblock meta %}

{% block content %}
<br><br><br><br>
<section>
    <div class="container">
        <div class="table-responsive-lg">
            {% for post in all_news %}
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <td>
                            <a href="{% url 'main:detail' post.id %}" title="">{{post.title}}</a>
                        </td>
                    </tr>
                </tbody>
            </table>

            <br><br>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock content %}

main/templates/main/searchresult.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Search Result | HypeUI</title>
{% endblock meta %}

{% block content %}
<br><br>
<section>
    <div class="container">
        <h1>
            &nbsp;&nbsp;&nbsp;&nbsp;
            Hasil Pencarian:
        </h1>
        <br><br>
        <div class="table-responsive-lg">
            {% for post in all_news %}
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <td>
                            <a href="{% url 'main:detail' post.id %}" title="">{{post.title}}</a>
                        </td>
                    </tr>
                </tbody>
            </table>

            <br><br>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

  <style>
    .checked {
      color:rgb(255, 217, 50);
    }
    .my-btn {
      background-color: inherit !important;
      border: 0 !important;
    }
  </style>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-secondary">
    <a class="navbar-brand" href="/"><img src="{% static 'img/HypeUI.png' %}" alt="Logo HypeUI" style="width: 30%;"></a>
    <form class="form-inline" method="POST" action="{% url 'main:search' %}">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Cari Berita" aria-label="Search" name="searched">
      <button class="btn btn-light my-2 my-sm-0" type="submit">Search</button>
    </form>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        {% if not user.is_authenticated %}
        <li>
          <a href="/userauth/login"><button type="button" class="btn btn-success">Login</button></a>
        </li>
        {% else %}
        <li>
          {% if user.is_staff %}
          <a href="/admin"><button type="button" class="btn btn-dark">Admin</button></a>
          {% else %}
          <button type="button" class="btn btn-dark">Hi {{request.user.username}}!</button>
          {% endif %}
        </li>
        <li>
          &nbsp;&nbsp;
        </li>
        <li>
          <a href="/add_new_post"><button type="button" class="btn btn-warning">Add new Post</button></a>
        </li>
        <li>
          &nbsp;&nbsp;
        </li>
        <li>
          <a href="/userauth/logout"><button type="button" class="btn btn-danger">Logout</button></a>
        </li>
        {% endif %}
      </ul>
  </nav>
  {% block content %}
  {% endblock content %}
</body>
</html>

userauth/templates/userauth/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<br><br><br><br>
<section id="login">    
    <h1 class="big-text text-center">Login</h1>
    <div class="container" style="max-width:60%">
        <div class="card">
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
            
                    <div class="form-group">
                        <label for="id_nama">Username:</label>
                        {{Form.nama}}
                    </div>
            
                    <div class="form-group">
                        <label for="id_password">Password:</label>
                        {{Form.password}}
                    </div>
                    {% if isError %}
                        <p style="color:red">{{Error}}</p>
                    {% endif %}
                    <button type="submit" class="btn btn-success btn-block">Login</button>
                </form>
                <p>Belum punya akun? <a href="{% url 'userauth:register' %}#register">Register</a></p>
            </div>
        </div>
    </div>
</section>

<br><br><br><br><br><br>

{% endblock content %}

userauth/templates/userauth/register.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Register</title>
{% endblock meta %}

{% block content %}
<br><br><br><br>
<section id="register">    
    <h1 class="big-text text-center">Register</h1>
    <div class="container" style="max-width:60%">
        <div class="card">
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
            
                    <div class="form-group">
                        <label for="id_nama">Username:</label>
                        {{Form.nama}}
                    </div>
            
                    <div class="form-group">
                        <label for="id_password">Password:</label>
                        {{Form.password}}
                    </div>
                    {% if isError %}
                        <p style="color:red">{{Error}}</p>
                    {% endif %}
                    <button type="submit" class="btn btn-success btn-block">Register</button>
                    <p>Sudah punya akun? <a href="{% url 'userauth:login' %}#login">Login</a></p>
                </form>
            </div>
        </div>
    </div>
</section>


<br><br><br><br><br><br>

{% endblock content %}